#!/usr/bin/ksh

DOWNLOG='down.log'
UPLOG='up.log'

for i in $(cat list)
do
	ping -c 1 $i > /dev/null
	if [ $? -eq 0 ]; then
		ssh -o ConnectTimeout=2 -o BactchMode=yes root@$i ksh < check_nfs.sh >> $UPLOG
	else
		echo "$i is down...skipping" >> $DOWNLOG
	fi
done
